version: 2
project_name: neocode

builds:
  - id: neocode
    main: ./cmd/neocode
    binary: neocode
    ldflags:
      - -s -w -X main.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats: ['tar.gz']
    format_overrides:
      - goos: windows
        formats: ['zip']
    name_template: "neocode_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

release:
  github:
    owner: WuSuBuDuoMing
    name: neocode
  prerelease: auto
