// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetContextUsage() {
  return window['go']['main']['App']['GetContextUsage']();
}

export function GetConversationMessages() {
  return window['go']['main']['App']['GetConversationMessages']();
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function NewConversation() {
  return window['go']['main']['App']['NewConversation']();
}

export function ResumeSession(arg1) {
  return window['go']['main']['App']['ResumeSession'](arg1);
}

export function SelectProvider() {
  return window['go']['main']['App']['SelectProvider']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
