// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig():Promise<Record<string, any>>;

export function GetContextUsage():Promise<Record<string, any>>;

export function GetConversationMessages():Promise<Array<Record<string, any>>>;

export function GetProviders():Promise<Array<Record<string, any>>>;

export function GetStatus():Promise<Record<string, any>>;

export function ListSessions():Promise<Array<Record<string, any>>>;

export function NewConversation():Promise<void>;

export function ResumeSession(arg1:string):Promise<Record<string, any>>;

export function SelectProvider():Promise<string>;

export function SendMessage(arg1:string):Promise<Record<string, any>>;

export function UpdateConfig(arg1:Record<string, any>):Promise<Record<string, any>>;
